expose_php=Off
memory_limit=256M
upload_max_filesize=50M
post_max_size=52M
max_execution_time=120
max_input_time=120
date.timezone=America/Sao_Paulo
session.cookie_httponly=1
session.cookie_samesite=Lax
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=192
realpath_cache_size=4096K
realpath_cache_ttl=600
